### PR TITLE
Exclude thread spawning and joining time from measurement

### PR DESCRIPTION
**Pull request by wvwwvwwv**
Hi,

Thanks a lot for this great benchmarking tool!

This PR simply adds a barrier to exclude thread spawning and joining time from the elapsed time measurement. Could you please review this?

### CODE REVIEW

**Review by jonhoo — APPROVED** [review]
Ah, good change, thanks!

**Comment by jonhoo** [comment]
Would you mind rebasing this onto `master` so that we get working CI again?

**Comment by wvwwvwwv** [comment]
Not at all, just rebased and fixed an issue with Rust 1.49.0!

**Review by jonhoo — APPROVED** [review]
One downside of this is that it'll hang forever if any of the benchmarker threads panic since they won't ever hit their second barrier. I think that's okay though. Their panic will still be printed.

**Comment by jonhoo** [comment]
Released as 0.4.3 :tada:

**Comment by wvwwvwwv** [comment]
> One downside of this is that it'll hang forever if any of the benchmarker threads panic since they won't ever hit their second barrier. I think that's okay though. Their panic will still be printed.

Oh, that would be problematic, though minor. I'll make a PR dealing with the issue.

**Pull request merged**
